### ISSUE TITLE
Mono.Linker.MarkException: Failed to resolve System.Int32 Plugin.LocalNotification.Resource/Boolean::enable_system_foreground_service_default

### ISSUE THREAD

**Issue by naman20sharma** [thudugala/Plugin.LocalNotification#155]
**Describe the bug**
Getting the following error after updating xamarin. forms to 5.0.0.2012, Xamarin.AndroidX.Work.Runtime to 2.5.0.1 and Plugin.LocalNotification from 4.1.4 to latest stable version 5.2.0. 

**To Reproduce**

1. Update xamarin.forms to 5.0.0.2012
2. build the solution in Release mode.

**Expected behavior**
It should build the application successfully.

**Screenshots**
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.Void MyWallet.Droid.Resource::UpdateIdValues()' in assembly: 'MyWallet.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 Plugin.LocalNotification.Resource/Boolean::enable_system_foreground_service_default
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	MyWallet.Android`

**Platform (please complete the following information):**
 - OS: Android
 - Version: 10

**Additional context**
I was using Plugin.LocalNotification version 4.1.4, and now I've updated latest version of Xamarin forms (5.0.0.2012) with Target Framework of android to 10, and netstandard2.1. But, the latest stable version of this plugin is giving this error while building the project.

**Comment by thudugala** [comment]
@naman20sharma Can you please attach a sample project
