### ISSUE TITLE
The plugin doesn't work on Android 6.0 & 7.0

### ISSUE THREAD

**Issue by Underground1337** [thudugala/Plugin.LocalNotification#197]
When I am trying to start the sample App in debug mode for Android 7.0 or 6.0 I am getting this error:

```
ADB0010: Mono.AndroidTools.InstallFailedException: Unexpected install output: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl498235248.tmp/base.apk (at Binary XML file line #26): <receiver> does not have valid android:name]

   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in C:\A\1\34\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 350
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass100_0.<InstallPackage>b__0(Task`1 t) in C:\A\1\34\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 803
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AndroidDeviceExtensions.<PushAndInstallPackageAsync>d__12.MoveNext() in C:\A\1\34\s\External\androidtools\Xamarin.AndroidTools\Devices\AndroidDeviceExtensions.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AndroidDeviceExtensions.<PushAndInstallPackageAsync>d__12.MoveNext() in C:\A\1\34\s\External\androidtools\Xamarin.AndroidTools\Devices\AndroidDeviceExtensions.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Android.Tasks.FastDeploy.<InstallPackage>d__101.MoveNext() in /Users/builder/azdo/_work/2/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 338
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Android.Tasks.FastDeploy.<InstallPackage>d__101.MoveNext() in /Users/builder/azdo/_work/2/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 355
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.Android.Tasks.FastDeploy.<RunTaskAsync>d__96.MoveNext() in /Users/builder/azdo/_work/2/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 212		 	0	
```
Starting it on Android 8.0 and above versions works fine. 

**To Reproduce**
1. Get the sample project 
2. Try to build the App for Android 7.0 or 6.0 

**Platform:**
 - OS: Android
 - Version 6.0 & 7.0

**Smartphone:**
 - Device: Pixel 2 XL Emulator & Samsung Tablet
 - OS: Android 6.0 & 7.0

**Additional context**
I am trying to use this package for my App and I need to be able to build it for Android 6.0 and above.
How can I make it Work?

**Comment by thudugala** [comment]
@Underground1337 what do you mean by "Try to build the App for Android 7.0 or 6.0".

**Comment by Underground1337** [comment]
@thudugala Sorry, I meant when I try to launch the app on an Android 6.0 or 7.0 device, I get the error message above.

**Comment by thudugala** [comment]
Hi, I am trying to use the last version of this plugin, but I get this error (only with android 7 or lower):

"ADB0010: Mono.AndroidTools.InstallFailedException: Unexpected install output: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl249737558.tmp/base.apk (at Binary XML file line #37): <receiver> does not have valid android:name]"
and, analyzing the AndroidManifest.xml generated by VisualStudio, there is an android:name which start with an uppercase letter:

```
<receiver android:enabled="true" android:exported="false" android:name="Plugin.LocalNotification.NotificationActionReceiver"/>
```

For this reason I am currently using the plugin version 5.2.0 (that does not generate that line in the Manifest file). I hope the problem can be solved.

Best Regards, Alessandro

**Comment by thudugala** [comment]
@Underground1337 Can please you try version 9.0.0-preview03 ?

**Comment by AlessandroDF** [comment]
Ok, with the version 9.0.0-preview03 the plugin works even on Android 6 & 7. 

However, with this new version there are some problems scheduling notifications: if I add the "Schedule" parameter (adding, for example, NotifyTime = DateTime.Now.AddSeconds(30)) I get this message: "**NotifyTime is earlier than DateTime.Now, notification ignored**"

**Comment by Underground1337** [comment]
I've tested Version 9.0.0-preview04 on Android 6 to 11 and had no problem with my Application.
Thanks for your effort : )
