### ISSUE TITLE
Android 7 - Unable to deploy application - install APK with Plugin.LocalNotification

### ISSUE THREAD

**Issue by Fra9944** [thudugala/Plugin.LocalNotification#203]
Hi!
When I compile with android 8.0+ it's working everything. But if I switch to Android 7.0:
With Plugin.LocalNotification installed there is the error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED.

You can reproduce it by creating a new xamarin Forms project, installing your nuget and try to debug it with an Android 7 device.

Error code is:
ADB0010: Mono.AndroidTools.InstallFailedException: Unexpected install output: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl260194836.tmp/base.apk (at Binary XML file line #42): <receiver> does not have valid android:name]

   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in C:\A\1\106\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 350
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass100_0.<InstallPackage>b__0(Task`1 t) in C:\A\1\106\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 803
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AndroidDeviceExtensions.<PushAndInstallPackageAsync>d__12.MoveNext() in C:\A\1\106\s\External\androidtools\Xamarin.AndroidTools\Devices\AndroidDeviceExtensions.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AndroidDeviceExtensions.<PushAndInstallPackageAsync>d__12.MoveNext() in C:\A\1\106\s\External\androidtools\Xamarin.AndroidTools\Devices\AndroidDeviceExtensions.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Android.Tasks.FastDeploy.<InstallPackage>d__101.MoveNext() in /Users/builder/azdo/_work/2/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 338
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Android.Tasks.FastDeploy.<InstallPackage>d__101.MoveNext() in /Users/builder/azdo/_work/2/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 355
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.Android.Tasks.FastDeploy.<RunTaskAsync>d__96.MoveNext() in /Users/builder/azdo/_work/2/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 212	 	0

I tried to clear Android Manifest but the error stuck.

The only way to solve this problem is uninstalling the nuget.
I'm targeting Android 11.
Xamarin and monoandroid are updated.

Devices:
- Honor 8 - Android 7.0;
- Pixel 2 - Android 7.0 [VIRTUAL];

Thank you.

**Comment by thudugala** [comment]
Can you try version 9 preview 4?

**Comment by Fra9944** [comment]
Yes, no deploy errors now.
I think is solved in 9.0.0 preview 4. 

Finally!

Thank you @thudugala
