### ISSUE TITLE
On my Google Pixel 3XL (updated to Android 12), when I try to schedule a notification using v9.1.0-preview01, I get the following message:

### ISSUE THREAD

**Issue by thudugala** [thudugala/Plugin.LocalNotification#220]
On my Google Pixel 3XL (updated to Android 12), when I try to schedule a notification using v9.1.0-preview01, I get the following message:

```
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

I don't see a notification after I schedule it. I uninstalled my app before trying to deploy the app through visual studio again.

_Originally posted by @gaurakshay in https://github.com/thudugala/Plugin.LocalNotification/discussions/217#discussioncomment-1553234_

**Comment by thudugala** [comment]
@gaurakshay Try 9.1.0-preview02

**Comment by tranb3r** [comment]
I'm also having this error. With 9.1.0-preview02.
Here is the stacktrace.

```
Java.Lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <dd8770963db64939be322a2c6d46563b>:0 
   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <dd8770963db64939be322a2c6d46563b>:0 
   at Android.App.PendingIntent.GetActivity (Android.Content.Context context, System.Int32 requestCode, Android.Content.Intent intent, Android.App.PendingIntentFlags flags) [0x00075] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.PendingIntent.cs:556 
   at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.ShowNow (Plugin.LocalNotification.NotificationRequest request) [0x0097d] in <28530818d3d847a7b6b10567b748a166>:0 
   at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.Show (Plugin.LocalNotification.NotificationRequest notificationRequest) [0x000d7] in <28530818d3d847a7b6b10567b748a166>:0 

```

**Comment by thudugala** [comment]
@tranb3r and @gaurakshay can you try changing PendingIntentFlags.CancelCurrent to see what value works for you?

in
Source/Plugin.LocalNotification/Platform/Droid/NotificationServiceImpl.cs
```cs
var pendingIntent = PendingIntent.GetActivity(Application.Context, request.NotificationId,
                notificationIntent,
                PendingIntentFlags.CancelCurrent);
```

Please direct reference the project

**Comment by tranb3r** [comment]
Adding PendingIntentFlags.Immutable seems to work.

```cs
var pendingIntent = PendingIntent.GetActivity(Application.Context, request.NotificationId,
                notificationIntent,
                PendingIntentFlags.CancelCurrent | PendingIntentFlags.Immutable);
```

**Comment by thudugala** [comment]
@tranb3r try v9.1.0-preview03

**Comment by tranb3r** [comment]
@thudugala 
LGTM. No more error on my test.
Thank you !

**Comment by gaurakshay** [comment]
With 9.1.0-preview03 I am getting exceptions (fresh deployment of the app):
```
[mpanyname.noti] Explicit concurrent copying GC freed 1223(137KB) AllocSpace objects, 0(0B) LOS objects, 90% free, 2728KB/26MB, paused 33us total 6.691ms
[0:] Serialized Request [{"Android":{"AutoCancel":true,"ChannelId":"AkshayNotificationTest","Color":{"Argb":null,"ResourceName":null},"Group":null,"IconLargeName":{"ResourceName":null,"Type":"drawable"},"IconSmallName":{"ResourceName":null,"Type":"drawable"},"IsGroupSummary":false,"IsProgressBarIndeterminate":null,"LedColor":null,"Ongoing":false,"Priority":1,"ProgressBarMax":null,"ProgressBarProgress":null,"TimeoutAfter":null,"VibrationPattern":null,"VisibilityType":1,"PendingIntentFlags":268435456},"BadgeNumber":0,"CategoryType":2,"Description":"Take an alert kind sir.","Image":{"Binary":null,"FilePath":null,"HasValue":false,"ResourceName":null},"iOS":{"HideForegroundAlert":false,"PlayForegroundSound":false},"NotificationId":1111,"ReturningData":"This is the returning data.","Schedule":{"NotifyAutoCancelTime":null,"NotifyRepeatInterval":null,"NotifyTime":"2021-11-03T14:22:38.994406-05:00","RepeatType":0,"AndroidAllowedDelay":"01:00:00"},"Silent":false,"Sound":"","Subtitle":"","Title":"Test"}]
[CompatibilityChangeReporter] Compat change id reported: 160794467; UID 10351; state: ENABLED
[0:] Java.Lang.IllegalArgumentException: com.companyname.notif: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <dd8770963db64939be322a2c6d46563b>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <dd8770963db64939be322a2c6d46563b>:0 
  at Android.App.PendingIntent.GetBroadcast (Android.Content.Context context, System.Int32 requestCode, Android.Content.Intent intent, Android.App.PendingIntentFlags flags) [0x00075] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.PendingIntent.cs:624 
  at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.ShowLater (Plugin.LocalNotification.NotificationRequest request) [0x00095] in <3bde372835d943c8afe8abd4f1d0c8aa>:0 
  at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.Show (Plugin.LocalNotification.NotificationRequest notificationRequest) [0x0005c] in <3bde372835d943c8afe8abd4f1d0c8aa>:0 
  at Notif.MainPage.ScheduleNotification (System.Object sender, System.EventArgs e) [0x000e0] in ~\source\repos\Notif\Notif\Notif\MainPage.xaml.cs:48 
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: com.companyname.notif: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at crc64ee486da937c010f4.ButtonRenderer.n_onClick(Native Method)
	at crc64ee486da937c010f4.ButtonRenderer.onClick(ButtonRenderer.java:104)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28676)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Going to try and use source code to build and deploy the app.

**Comment by gaurakshay** [comment]
Using the source code directly with the `PendingIntentFlags.Immutable` seems to work perfectly fine.

**Comment by gaurakshay** [comment]
Stack trace when referencing source code directly without updating the flags (only `PendingIntentFlags.UpdateCurrent`):

```
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <dd8770963db64939be322a2c6d46563b>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <dd8770963db64939be322a2c6d46563b>:0 
  at Android.App.PendingIntent.GetBroadcast (Android.Content.Context context, System.Int32 requestCode, Android.Content.Intent intent, Android.App.PendingIntentFlags flags) [0x00075] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-31/mcw/Android.App.PendingIntent.cs:624 
  at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.ShowLater (Plugin.LocalNotification.NotificationRequest request) [0x0008a] in D:\github\Plugin.LocalNotification\Source\Plugin.LocalNotification\Platform\Droid\NotificationServiceImpl.cs:202 
  at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.Show (Plugin.LocalNotification.NotificationRequest notificationRequest) [0x0005c] in D:\github\Plugin.LocalNotification\Source\Plugin.LocalNotification\Platform\Droid\NotificationServiceImpl.cs:174 
  at Notif.MainPage.ScheduleNotification (System.Object sender, System.EventArgs e) [0x000e0] in C:\Users\agaur\source\repos\Notif\Notif\Notif\MainPage.xaml.cs:48 
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: com.companyname.notif: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at crc64ee486da937c010f4.ButtonRenderer.n_onClick(Native Method)
	at crc64ee486da937c010f4.ButtonRenderer.onClick(ButtonRenderer.java:104)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28676)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
