### ISSUE TITLE
System.NullReferenceException on Show (11.1.0)

### ISSUE THREAD

**Issue by Wandtket** [thudugala/Plugin.LocalNotification#477]
When showing a notification the notification will pop as expected but then throw a System.NullReferenceException immediately afterwards.

1. Use the setup project.
2. Pop a notification.

![image](https://github.com/thudugala/Plugin.LocalNotification/assets/13137508/a15236b9-e11a-45e5-adde-5a275f76182c)

 - Device: Emulator
 - OS: Android 10.0 API 29
 - Version: 11.1.0

**Comment by thudugala** [comment]
@Wandtket Can you please attach a sample project?

**Comment by Wandtket** [comment]
@thudugala I can't seem to reproduce it in a sample project which is a little frustrating,

Sorry for the delay, here's the output from the NullReferenceException:

`{System.NullReferenceException: Object reference not set to an instance of an object.
   at Plugin.LocalNotification.NotificationImage.get_HasValue()
   at System.Object.HasValueGetter(Object )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Plugin.LocalNotification.NotificationImage, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]].OnTryWrite(Utf8JsonWriter writer, NotificationImage value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[Plugin.LocalNotification.NotificationImage, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]].TryWrite(Utf8JsonWriter writer, NotificationImage& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Plugin.LocalNotification.NotificationImage, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]].GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]].OnTryWrite(Utf8JsonWriter writer, NotificationRequest value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]].TryWrite(Utf8JsonWriter writer, NotificationRequest& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.ListOfTConverter`2[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]].OnWriteResume(Utf8JsonWriter writer, List`1 value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]].OnTryWrite(Utf8JsonWriter writer, List`1 value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter writer, List`1& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore(Utf8JsonWriter writer, List`1& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Serialize(Utf8JsonWriter writer, List`1& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[List`1](List`1& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[List`1](List`1 value, JsonSerializerOptions options)
   at Plugin.LocalNotification.Json.NotificationSerializer.Serialize[List`1](List`1 value)
   at Plugin.LocalNotification.LocalNotificationCenter.GetRequestListSerialize(List`1 requestList)
   at Plugin.LocalNotification.Platforms.NotificationRepository.SetList(String key, List`1 list)
   at Plugin.LocalNotification.Platforms.NotificationRepository.SetDeliveredList(List`1 list)
   at Plugin.LocalNotification.Platforms.NotificationRepository.AddDeliveredRequest(NotificationRequest request)
   at Plugin.LocalNotification.Platforms.NotificationServiceImpl.ShowNow(NotificationRequest request)}`

**Comment by Wandtket** [comment]
@thudugala 

I had thought since my original project was created on .net 6 something might've been keeping it from working properly, I created a new project starting on .net 8 and it worked fine, then I fired up the old project and for some reason it started working properly. Which is strange, I uninstalled the app from the emulator and started from scratch. 

Everything appears to be working fine now, sorry for the trouble.

**Comment by peter-bozovic** [comment]
I didn't notice this error while developing or in released application that I installed, but it is reported by Android Play Console under Android Vitals !

It's:
Exception android.runtime.JavaProxyThrowable: [System.NullReferenceException]: Object reference not set to an instance of an object
  at Plugin.LocalNotification.NotificationImage.get_HasValue
  at System.Object.HasValueGetter

It affects any Android versions, and mostly Samsung and Xiaomi phones

From the error message, probably something happening when receiving Image attached to the notification ?

**Comment by chnoergaard** [comment]
I updated my project from .NET 7.0 to 8.0, and started getting these errors on version 11.1.2. Going back to version 10.1.8 fixed it but introduced other problems with permissions so I had to go back to the latest version.

At first I got the "[System.NullReferenceException]: Object reference not set to an instance of an object"-exceptions when trying to use Cancel or Clear methods when running the code in Visual Studio on an Emulator. I could'nt figure out what it was and it wasn't until CrashLytics came onboard that it mentioned this exact error so I finally could see what was the main cause.

The code works fine when running Debug or Release from Visual Studio. But when added to Google Play it crashes the app with the error:

```
Fatal Exception: android.runtime.JavaProxyThrowable
[System.NullReferenceException]: Object reference not set to an instance of an object
Plugin.LocalNotification.NotificationImage.get_HasValue
System.Object.HasValueGetter
System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetMemberAndWriteJson
System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Plugin.LocalNotification.NotificationImage, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]].OnTryWrite
System.Text.Json.Serialization.JsonConverter`1[[Plugin.LocalNotification.NotificationImage, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]].TryWrite
System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Plugin.LocalNotification.NotificationImage, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]].GetMemberAndWriteJson
System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]].OnTryWrite
System.Text.Json.Serialization.JsonConverter`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]].TryWrite
System.Text.Json.Serialization.Converters.ListOfTConverter`2[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]].OnWriteResume
System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]].OnTryWrite
System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite
System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore
System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.Collections.Generic.List`1[[Plugin.LocalNotification.NotificationRequest, Plugin.LocalNotification, Version=11.1.2.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Serialize
System.Text.Json.JsonSerializer.WriteString
System.Text.Json.JsonSerializer.Serialize
Plugin.LocalNotification.Json.NotificationSerializer.Serialize
Plugin.LocalNotification.LocalNotificationCenter.GetRequestListSerialize
Plugin.LocalNotification.Platforms.NotificationRepository.SetList
Plugin.LocalNotification.Platforms.NotificationRepository.SetDeliveredList
Plugin.LocalNotification.Platforms.NotificationRepository.RemoveByDeliveredIdList
Plugin.LocalNotification.Platforms.NotificationServiceImpl.Cancel
Helpicine.ViewModels.ReminderPageViewModel.CancelAndClearLocalNotificationsByReminderId
Helpicine.ViewModels.ReminderPageViewModel+<DeleteReminder>d__31.MoveNext
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
System.Threading.Tasks.Task+<>c.<ThrowAsync>b__128_0
Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0
Java.Lang.Thread+RunnableImplementor.Run
Java.Lang.IRunnableInvoker.n_Run
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V
mono.java.lang.RunnableImplementor.n_run (RunnableImplementor.java)
mono.java.lang.RunnableImplementor.run (RunnableImplementor.java:31)
android.os.Handler.handleCallback (Handler.java:900)
```

I've tried removing Plugin.Localnotification from NuGet, closed VS, removed bin and obj folders, reopened VS and re-installed Plugin.Localnotification via NuGet again but it did'nt work.
I've also tried adding an Image to the NotificationRequest just to see if it could help with the Get method, but this also had no effect.

**Comment by chnoergaard** [comment]
Okay, so I've tried a few things more without success.

I added the latest System.Text.Json to the project.
I added a DisplayAlert to check values just before the Cancel and Clear method, and the values were these:

HasValue: false
FilePath: ""
ResourceName: ""
Binary: System.Byte[]

So I can't see an issue with the data. But the error still makes the app crash exactly when the Cancel or Clear method are called.

**Comment by chnoergaard** [comment]
Well, I finally got it working but how exactly eludes me. I'll list the things I can remember I did or tried, so hopefully it can help someone else with the issue:

- I had a .nuget folder in my project root but I had actually moved all nuget package installation to C:\n, due to some iOS LongPath issue with Windows, so I removed this folder as it was noy being used and I was thinking it might cause conflicts
- I tried setting up a custom local notification system using Microsoft.Maui.Essentials package, but uninstalled it again after I went back to trying to solve this issue
- I noticed that the Package for 11.1.2 had multiple frameworks for net8.0. When the problem started my project was running net8.0-android34.0 but I changed this to net8.0 in my .csproj file because I was unsure if the issue had something to do with API 34.0. Today I changed it back from net8.0-android (though I had it set to net8.0, so I dunno how the -android part got added) to net8.0-android34.0 and also noticed this particular framework wants Xamarin.GooglePlayServices.Location, so I also installed this package.. I actually thought it got auto-installed since it is a dependency

Any or several of these might have helped solve the issue. Personally I think it was the latter.

**Comment by LeoJHarris** [comment]
Had this issue as well, rolled back to version 10.1.8 works for now but will investigate further when we need to update this packages again.

**Comment by LeoJHarris** [comment]
Still causing us issues from the internal testing track on the play store, I think 10.1.8 worked but we have since updated to the 11.1.4 and I wont be rolling back to check as we need to keep this library updated due to other library dependencies.

@thudugala any ideas?

**Comment by LeoJHarris** [comment]
Am I missing something or are we meant to set the `NotificationImage` given this is a `Object reference not set to an instance of an object` on `NotificationImage.get_HasValue`

**Comment by LeoJHarris** [comment]
@thudugala  Whist this does not address the issue why the Image maybe null, should we at least null check it to avoid the exception?

```csharp
internal static string GetRequestListSerialize(List<NotificationRequest> requestList)
{
    foreach (var request in requestList)
    {
        if (request.Image != null && request.Image.Binary != null && request.Image.Binary.Length > 90000)
        {
            request.Image.Binary = new byte[0];
        }
    }
    var serializedRequestList = Serializer.Serialize(requestList);
    return serializedRequestList;
}
```

**Comment by LeoJHarris** [comment]
@thudugala any update we are still experiencing the problem...

**Comment by LeoJHarris** [comment]
@thudugala This crash is now our most reported crash Android i.e.

```
Plugin.LocalNotification.NotificationImage.get_HasValue + 0x20
android.runtime.JavaProxyThrowable - [System.NullReferenceException]: Object reference not set to an instance of an object
```

We really need to understand if this something resolvable or will be investigate, since its every hard to reproduce I'm not sure our feasible it will be to provide a sample repo but what is this issue waiting on to get some action? If the issue remains stale unfortunately we'll be dropping this plugin due to customer impact.

**Comment by LeoJHarris** [comment]
@thudugala Legend! 🥇 I noticed your latest NuGet release to address the null exception on the image, I've since installed v12.0 and we plan on a new new app release in the coming days to monitor.

**Comment by thudugala** [comment]
@LeoJHarris Sorry for the late reply. 

Please make a PR directly when you see an issue

**Comment by LeoJHarris** [comment]
@thudugala will do!

**Comment by LeoJHarris** [comment]
I could be wrong but I think this issue is still occurring even on the latest v12.0.0

```
Plugin.LocalNotification.NotificationImage.get_HasValue + 0x20
android.runtime.JavaProxyThrowable - [System.NullReferenceException]: Object reference not set to an instance of an object
```

Regressed issue on our latest build where we updated to v12.0.0, anyone else still seeing this?

**Comment by LeoJHarris** [comment]
@thudugala I'm in the process of adding a unit test project using similar setup to the MAUI community toolkit

```csproj
PackageReference Include="FluentAssertions" Version="8.2.0" />
		<PackageReference Include="FluentAssertions.Analyzers" Version="0.34.1" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
		<PackageReference Include="xunit.v3" Version="2.0.1" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.2" />
```

**Comment by LeoJHarris** [comment]
@thudugala I have added a unit test for checking null notification image, test is passing

public bool HasValue => string.IsNullOrWhiteSpace(ResourceName) == false ||
                        string.IsNullOrWhiteSpace(FilePath) == false ||
                        (Binary?.Length > 0);

Seems to fix the Null Object References on the Binary where as previous test was failing.

**Comment by LeoJHarris** [comment]
@thudugala I can PR shortly for your review.
